import "./globals.css";
import { Josefin_Sans, Source_Serif_Pro } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
config.autoAddCss = false;

const sourceSerifPro = Source_Serif_Pro({
	weight: ["200", "300", "400", "600", "700", "900"],
	subsets: ["latin"],
	variable: "--font-source-serif-pro",
});
const josefinSans = Josefin_Sans({
	subsets: ["latin"],
	variable: "--font-josefin",
});

export const metadata = {
	title: "My Blog",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={`${josefinSans.variable} ${sourceSerifPro.variable}`}
		>
			<body>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
